on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: windows-latest

    steps:
      - name:'Testing Github action '
        run: pwd

        - name:'Testing printing '
        run: mazen
